### ISSUE TITLE
ServerIdentity.URL is not repsected in cothority-js

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1838] opened 2019-05-01 09:44 UTC
The cothority-js does not respect a `ServerIdentity.URL`, so the following happens in the explorer:

```
WebSocket connection to 'wss://conode.dedis.ch:7001/Skipchain/GetAllSkipChainIDs' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
```

This is because the ServerIdentity of conode.dedis.ch has a URL that does not follow port+1.

**Comment by jeffallen** [comment] 2019-05-07 08:29
I investigated this and it is because skipchain-rpc.ts's getUpdateChain needs to create a new SkipchainRPC out of the last block's roster in order to follow a chain across roster changes. In this case, the last block was from early in the chain, when the rosters did not have the URL set yet.

As far as I can see, this is not a bug, but it is a bit of a design fault. By design, there is no way to modify the roster used in the past, but if the reality changes later (ip address change, switch to https:// websocket url, etc) then you risk to not be able to follow the skipchain.

The newRoster field of the forward links could help with this, but they are not used by getUpdateChain. Should they be?

**Comment by Gilthoniel** [comment] 2019-05-09 13:32
Hm yeah, for that kind of chain where the roster changes so that the genesis roster is offline (or in that switch to a secure protocol) the only solution I see is to force a roster to be used every time. We could add a parameter `keepRoster = false` that prevent the roster update when set to true.

**Comment by Gilthoniel** [comment] 2019-05-09 13:33
Using _newRoster_ doesn't necessarily help because it could still be an offline roster.

**Comment by jeffallen** [comment] 2019-05-09 13:37
I'm going to close this as will not fix for the moment, when we see a case of this happening and it is critical to fix, then we'll revisit it, looking for the best fix to the situation driving the fix.

**Closed by jeffallen** 2019-05-09 13:37 UTC
Labels: bug
